// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactNative = require("react-native");

function make(children) {
  return ReasonReact.wrapJsForReason(ReactNative.ViewNativeComponent, { }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
